language: node_js

matrix:
  include:
  - node_js: '6'
  - node_js: '7'
  - node_js: '8'

after_script:
- npm run coverage

script: validate-commit-msg "$(git log -1 --pretty=%B)" && npm test

notifications:
  email: false

before_install: ".travis/before_install.sh"
after_success: ".travis/after_success.sh"
